version: '3.8'

services:
  datastore:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
  
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_URL=datastore
    depends_on:
      - datastore
